### ISSUE TITLE
No parametrization with arguments

### ISSUE THREAD

**Issue by nobody43** [pgagnidze/updo#6]
It's a natural convention to use first argument as main input, e.g.
`updo https://example.com`
should be interpreted as:
`updo --url https://example.com`

And I think even the protocol should be guessed automatically.

Anyway, thanks for the tool.

**Comment by pgagnidze** [comment]
Implemented in https://github.com/pgagnidze/updo/pull/10

**Comment by nobody43** [comment]
Thanks!
