### ISSUE TITLE
Can't push branch to add Dockerfile

### ISSUE THREAD

**Issue by o6uoq** [pgagnidze/updo#9]
The project says it allows contributions but there's no way to create a branch to trigger a Pull Request.

I want to add a Dockerfile to run this via a container:

**Dockerfile**
```
❯ bat Dockerfile
# Use the latest version of Golang as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Go application source code into the container
COPY . .

# Build the Go application
RUN go build

# Command to run the executable
CMD ["./updo"]
```

To use, simply run:

```
docker build -t updo .
docker run -it updo ./updo --url <website-url> [options]
```

**Comment by pgagnidze** [comment]
Hi @o6uoq Thank you for your suggestion!

If you would like to contribute to this repository, please follow these steps:

1. Fork this repository.
2. Make the necessary changes to the forked repository.
3. Contribute the changes back to the main repository.

Please refer to the screenshot below.

<img width="512" alt="Screenshot 2024-05-03 at 1 24 59 PM" src="https://github.com/pgagnidze/updo/assets/17541283/061a8b43-4388-4d7a-ab50-4df1a4991aff">

If you have any questions, feel free to ask. We can continue the discussion regarding proposed enhancement in your pull request.

**Comment by pgagnidze** [comment]
@o6uoq Thanks! I added the comment in your PR. Please share your thoughts.

**Comment by pgagnidze** [comment]
Closing this issue as you resolved an issue with opening the PR.
